# Generated by Django 5.0.1 on 2025-12-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_id', models.CharField(max_length=100, unique=True)),
                ('caption', models.TextField(blank=True)),
                ('media_type', models.CharField(max_length=20)),
                ('media_url', models.URLField(max_length=500)),
                ('permalink', models.URLField(max_length=500)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='core_instag_timesta_17d4b7_idx')],
            },
        ),
    ]
