# Generated by Django 5.0.1 on 2025-12-09 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full legal name', max_length=100)),
                ('display_name', models.CharField(blank=True, help_text="Name shown on website (e.g., 'Coach K', 'Tray')", max_length=50)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', unique=True)),
                ('role', models.CharField(choices=[('head_coach', 'Head Coach'), ('assistant_coach', 'Assistant Coach'), ('trainer', 'Trainer'), ('skills_coach', 'Skills Coach'), ('founder', 'Founder')], max_length=30)),
                ('title', models.CharField(blank=True, help_text="Custom title (e.g., 'Head Coach & Trainer')", max_length=100)),
                ('bio', models.TextField(blank=True, help_text='Coach biography')),
                ('photo_url', models.URLField(blank=True, help_text='URL to coach photo', max_length=500)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('instagram_handle', models.CharField(blank=True, help_text="Instagram handle without @ (e.g., 'traygotbounce')", max_length=30)),
                ('specialties', models.CharField(blank=True, help_text="Comma-separated list of specialties (e.g., 'ball handling, shooting, defense')", max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Coach',
                'verbose_name_plural': 'Coaches',
                'ordering': ['order', 'name'],
            },
        ),
    ]
