# Generated by Django 5.0.1 on 2025-12-18 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_contact_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printify_api_key', models.CharField(blank=True, help_text='Printify API token from Account > Connections', max_length=500)),
                ('printify_shop_id', models.CharField(blank=True, help_text='Printify Shop ID', max_length=50)),
                ('printify_shop_name', models.CharField(blank=True, help_text='Printify Shop name (for display)', max_length=100)),
                ('printify_connected_at', models.DateTimeField(blank=True, help_text='When Printify was connected', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Integration Settings',
                'verbose_name_plural': 'Integration Settings',
            },
        ),
    ]
