# Generated by Django 5.0.1 on 2025-12-18 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_integration_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationsettings',
            name='printify_api_key',
            field=models.CharField(blank=True, help_text='Printify API token from Account > Connections', max_length=1000),
        ),
    ]
