# Generated by Django 5.0.1 on 2025-12-18 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_integrationsettings_printify_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationsettings',
            name='printify_api_key',
            field=models.TextField(blank=True, help_text='Printify API token from Account > Connections'),
        ),
    ]
