# Generated by Django 5.0.1 on 2026-01-05 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_integrationsettings_printify_api_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(help_text="Friendly name (e.g., 'NJ Stars Official')", max_length=100)),
                ('instagram_username', models.CharField(help_text="Instagram handle without @ (e.g., 'njstarselite_aau')", max_length=50)),
                ('instagram_user_id', models.CharField(help_text='Instagram/Facebook User ID (from API)', max_length=50)),
                ('access_token', models.TextField(help_text='Long-lived access token from Instagram Graph API')),
                ('token_expires_at', models.DateTimeField(help_text='When the token expires (60 days from issue)')),
                ('token_issued_at', models.DateTimeField(auto_now_add=True, help_text='When this token was first added')),
                ('last_refreshed_at', models.DateTimeField(blank=True, help_text='Last time the token was refreshed', null=True)),
                ('app_id', models.CharField(blank=True, help_text='Meta App ID (for token refresh)', max_length=50)),
                ('app_secret', models.CharField(blank=True, help_text='Meta App Secret (for token refresh)', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether to use this account for fetching posts')),
                ('is_primary', models.BooleanField(default=False, help_text='Primary account (used when no specific account requested)')),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='Last successful post sync', null=True)),
                ('last_error', models.TextField(blank=True, help_text='Last error message (cleared on success)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Instagram Credential',
                'verbose_name_plural': 'Instagram Credentials',
                'ordering': ['-is_primary', 'account_name'],
            },
        ),
    ]
