# Generated by Django 5.0.1 on 2026-01-06 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_instagram_credential'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramcredential',
            name='app_id',
        ),
        migrations.RemoveField(
            model_name='instagramcredential',
            name='app_secret',
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='media_url',
            field=models.URLField(max_length=2000),
        ),
    ]
