# Generated by Django 5.0.1 on 2026-01-06 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_extend_media_url_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationsettings',
            name='contact_email',
            field=models.EmailField(default='contact@leag.app', help_text='Email address that receives contact form submissions', max_length=254),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='instagram_url',
            field=models.URLField(blank=True, default='https://instagram.com/njstarselite_aau', help_text='Instagram profile URL for footer/social links'),
        ),
    ]
