# Generated by Django 5.0.1 on 2025-12-15 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_allow_guest_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='waiver_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='waiver_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='waiver_signer_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='waiver_version',
            field=models.CharField(default='2024.1', max_length=20),
        ),
    ]
