# Generated by Django 5.0.1 on 2025-12-18 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_add_waiver_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('cash', 'Cash'), ('check', 'Check'), ('free', 'Free Event')], default='stripe', help_text='How this registration was paid', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='medical_notes',
            field=models.TextField(blank=True, help_text='Conditions, medications, etc.'),
        ),
    ]
