# Generated by Django 5.0.1 on 2025-12-05 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField()),
                ('event_type', models.CharField(choices=[('tryout', 'Tryout'), ('open_gym', 'Open Gym'), ('tournament', 'Tournament'), ('practice', 'Practice'), ('camp', 'Camp'), ('game', 'Game')], max_length=20)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('requires_payment', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Price for this event', max_digits=10, null=True)),
                ('stripe_price_id', models.CharField(blank=True, help_text='Stripe Price ID for this event', max_length=255)),
                ('max_participants', models.IntegerField(blank=True, help_text='Leave blank for unlimited', null=True)),
                ('registration_open', models.BooleanField(default=True)),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_datetime'],
                'indexes': [models.Index(fields=['event_type', 'start_datetime'], name='events_even_event_t_afaaa8_idx'), models.Index(fields=['registration_open', 'start_datetime'], name='events_even_registr_f90512_idx')],
            },
        ),
    ]
