# Generated by Django 5.0.1 on 2025-12-10 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name for this calendar (e.g., 'Master Schedule')", max_length=100)),
                ('ical_url', models.URLField(help_text='iCal/ICS feed URL (e.g., Google Calendar public iCal URL)', max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable syncing from this calendar')),
                ('default_event_type', models.CharField(choices=[('tryout', 'Tryout'), ('open_gym', 'Open Gym'), ('tournament', 'Tournament'), ('practice', 'Practice'), ('camp', 'Camp'), ('game', 'Game')], default='practice', help_text='Default event type for imported events', max_length=20)),
                ('auto_publish', models.BooleanField(default=False, help_text='Automatically make synced events public')),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Last successful sync time', null=True)),
                ('last_sync_count', models.IntegerField(default=0, help_text='Number of events from last sync')),
                ('sync_error', models.TextField(blank=True, help_text='Last sync error message (if any)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Calendar Source',
                'verbose_name_plural': 'Calendar Sources',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='external_uid',
            field=models.CharField(blank=True, db_index=True, help_text='Unique ID from external calendar (iCal UID)', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='is_locally_modified',
            field=models.BooleanField(default=False, help_text='If true, sync will not overwrite local changes'),
        ),
        migrations.AddField(
            model_name='event',
            name='calendar_source',
            field=models.ForeignKey(blank=True, help_text='Source calendar this event was synced from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.calendarsource'),
        ),
    ]
