# Generated by Django 5.0.1 on 2025-12-18 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_add_event_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarsource',
            name='default_event_type',
            field=models.CharField(choices=[('tryout', 'Tryout'), ('open_gym', 'Open Gym'), ('tournament', 'Tournament'), ('practice', 'Practice'), ('camp', 'Camp'), ('game', 'Game'), ('skills', 'Skills'), ('social', 'Team Social')], default='practice', help_text='Default event type for imported events', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('tryout', 'Tryout'), ('open_gym', 'Open Gym'), ('tournament', 'Tournament'), ('practice', 'Practice'), ('camp', 'Camp'), ('game', 'Game'), ('skills', 'Skills'), ('social', 'Team Social')], max_length=20),
        ),
    ]
