# Generated by Django 5.0.1 on 2025-12-06 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_featured_images', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='newsletter_heading',
            field=models.CharField(blank=True, default='Stay Updated', max_length=120),
        ),
        migrations.AddField(
            model_name='homepage',
            name='newsletter_subheading',
            field=models.CharField(blank=True, default='Get the latest news and updates', max_length=240),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_newsletter_signup',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='grade',
            field=models.CharField(blank=True, help_text="e.g., '10th Grade' or 'Sophomore'", max_length=20),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='height',
            field=models.CharField(blank=True, help_text='e.g., \'6\'2"\'', max_length=20),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='position',
            field=models.CharField(blank=True, choices=[('PG', 'Point Guard'), ('SG', 'Shooting Guard'), ('SF', 'Small Forward'), ('PF', 'Power Forward'), ('C', 'Center')], max_length=2),
        ),
    ]
