# Generated by Django 5.0.1 on 2025-12-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_blogpage_author_blogpage_featured_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='category',
            field=models.CharField(choices=[('news', 'News'), ('tryouts', 'Tryouts'), ('camp', 'Camp'), ('tournament', 'Tournament'), ('merch', 'Merch Drop'), ('sale', 'Sale'), ('announcement', 'Announcement')], default='news', help_text='Category for the post (used for filtering and display)', max_length=20),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_tagline',
            field=models.CharField(blank=True, help_text="Secondary tagline (e.g., 'Built for Rising Stars.')", max_length=120),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_heading',
            field=models.CharField(blank=True, help_text="Main headline (e.g., 'Elite Training.')", max_length=120),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_subheading',
            field=models.CharField(blank=True, help_text='Paragraph text below the headline', max_length=240),
        ),
    ]
