# Generated by Django 5.0.1 on 2025-12-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_add_hero_tagline_and_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='huddle_limit',
            field=models.IntegerField(default=3, help_text='Number of posts to show (1-12)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='merch_limit',
            field=models.IntegerField(default=3, help_text='Number of products to show (1-12)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_huddle_section',
            field=models.BooleanField(default=True, help_text='Show The Huddle news feed section'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_merch_section',
            field=models.BooleanField(default=True, help_text='Show featured merch section'),
        ),
    ]
