# Generated by Django 5.0.1 on 2025-12-10 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0008_complete_bag_rename'),
        ('registrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DuesAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_good_standing', models.BooleanField(default=True)),
                ('last_payment_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dues_accounts', to='payments.subscription')),
            ],
            options={
                'verbose_name': 'Dues Account',
                'verbose_name_plural': 'Dues Accounts',
            },
        ),
        migrations.CreateModel(
            name='DuesTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('charge', 'Charge'), ('payment', 'Payment'), ('credit', 'Credit'), ('refund', 'Refund')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='portal.duesaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dues_transactions', to=settings.AUTH_USER_MODEL)),
                ('event_registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dues_transactions', to='registrations.eventregistration')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dues_transactions', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Dues Transaction',
                'verbose_name_plural': 'Dues Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_ins_performed', to=settings.AUTH_USER_MODEL)),
                ('event_registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='check_in', to='registrations.eventregistration')),
            ],
            options={
                'verbose_name': 'Event Check-In',
                'verbose_name_plural': 'Event Check-Ins',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('jersey_number', models.CharField(blank=True, max_length=10)),
                ('position', models.CharField(blank=True, max_length=50)),
                ('team_name', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='players/')),
                ('photo_url', models.URLField(blank=True, max_length=500)),
                ('medical_notes', models.TextField(blank=True)),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_phone', models.CharField(max_length=20)),
                ('emergency_contact_relationship', models.CharField(default='Parent/Guardian', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='duesaccount',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dues_account', to='portal.player'),
        ),
        migrations.CreateModel(
            name='PromoCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_type', models.CharField(choices=[('referral', 'Referral Bonus'), ('loyalty', 'Loyalty Reward'), ('promo', 'Promotional Credit'), ('adjustment', 'Account Adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_credits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Promo Credit',
                'verbose_name_plural': 'Promo Credits',
                'ordering': ['expires_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_method_id', models.CharField(max_length=255, unique=True)),
                ('card_brand', models.CharField(max_length=50)),
                ('card_last4', models.CharField(max_length=4)),
                ('card_exp_month', models.IntegerField()),
                ('card_exp_year', models.IntegerField()),
                ('is_default', models.BooleanField(default=False)),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Payment Method',
                'verbose_name_plural': 'Saved Payment Methods',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('parent', 'Parent/Guardian'), ('player', 'Player (13+)'), ('staff', 'Staff')], default='parent', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(default='NJ', max_length=50)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('waiver_signed_at', models.DateTimeField(blank=True, help_text='Date/time the liability waiver was signed', null=True)),
                ('waiver_version', models.CharField(blank=True, help_text="Version of waiver that was signed (e.g., '2024.1')", max_length=20)),
                ('waiver_signer_name', models.CharField(blank=True, help_text='Name as signed on the waiver', max_length=200)),
                ('auto_pay_enabled', models.BooleanField(default=False)),
                ('notification_email', models.BooleanField(default=True)),
                ('notification_sms', models.BooleanField(default=False)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='GuardianRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('parent', 'Parent'), ('guardian', 'Legal Guardian'), ('grandparent', 'Grandparent'), ('relative', 'Other Relative'), ('coach', 'Coach'), ('other', 'Other')], default='parent', max_length=20)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary contact for this player')),
                ('can_pickup', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_relationships', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_relationships', to='portal.player')),
            ],
            options={
                'verbose_name': 'Guardian Relationship',
                'verbose_name_plural': 'Guardian Relationships',
                'unique_together': {('guardian', 'player')},
            },
        ),
    ]
