# Generated by Django 5.0.1 on 2025-12-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_add_team_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text="User's date of birth for age verification", null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='player_profile_enabled',
            field=models.BooleanField(default=False, help_text='Enable player view option on dashboard (for parents/staff who also play)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='registered_as',
            field=models.CharField(choices=[('parent', 'Parent'), ('player', 'Player')], default='parent', help_text='Role selected during registration', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_parent_dashboard',
            field=models.BooleanField(default=False, help_text='Show parent dashboard tab (for staff/players who are also parents)'),
        ),
    ]
