# Generated by Django 5.0.1 on 2025-12-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_add_dashboard_prefs_and_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='google_sheets_credentials',
            field=models.TextField(blank=True, null=True),
        ),
    ]
