# Generated by Django 5.0.1 on 2025-12-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='best_selling',
            field=models.BooleanField(default=False, help_text='Mark as bestseller'),
        ),
        migrations.AddField(
            model_name='product',
            name='on_sale',
            field=models.BooleanField(default=False, help_text="Show 'On Sale' badge"),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False, help_text='Show in featured products section'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['best_selling', 'is_active'], name='payments_pr_best_se_fe79d7_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['on_sale', 'is_active'], name='payments_pr_on_sale_666207_idx'),
        ),
    ]
