# Generated by Django 5.0.1 on 2025-12-09 21:51

import apps.payments.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_add_cart_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='Legacy single image URL', max_length=500),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Product image (recommended: 800x800px or larger)', upload_to=apps.payments.models.product_image_path)),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for accessibility', max_length=200)),
                ('is_primary', models.BooleanField(default=False, help_text='Set as the main product image')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Order in the carousel (lower = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='payments.product')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
                'indexes': [models.Index(fields=['product', 'sort_order'], name='payments_pr_product_5f0b01_idx')],
            },
        ),
    ]
