# Generated by Django 5.0.1 on 2025-12-09 22:00

import apps.payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_product_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(blank=True, help_text='Or paste an image URL (e.g., from Unsplash)', max_length=500),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image file (recommended: 800x800px or larger)', null=True, upload_to=apps.payments.models.product_image_path),
        ),
    ]
