# Generated by Django 5.0.1 on 2025-12-10 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_rename_cart_to_bag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='bagitem',
            old_name='cart',
            new_name='bag',
        ),
        migrations.AlterUniqueTogether(
            name='bagitem',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='bag',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, help_text='Session key for guest bags', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='bag',
            name='user',
            field=models.OneToOneField(blank=True, help_text="Authenticated user's bag", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bag', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bagitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bag_items', to='payments.product'),
        ),
        migrations.AlterUniqueTogether(
            name='bagitem',
            unique_together={('bag', 'product', 'selected_size', 'selected_color')},
        ),
        migrations.AlterModelTable(
            name='bag',
            table='payments_cart',
        ),
        migrations.AlterModelTable(
            name='bagitem',
            table='payments_cartitem',
        ),
    ]
