# Generated by Django 5.0.1 on 2025-12-11 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_complete_bag_rename'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fulfillment_type',
            field=models.CharField(choices=[('pod', 'Print on Demand (Printify)'), ('local', 'Local/Vendor (Coach Delivery)')], default='local', help_text='How this product is fulfilled: POD via Printify or local coach delivery', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='manage_inventory',
            field=models.BooleanField(default=True, help_text='Track inventory locally. Set False for POD products (always in stock)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='printify_product_id',
            field=models.CharField(blank=True, help_text='Printify Product ID - required for POD products', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='printify_variant_id',
            field=models.CharField(blank=True, help_text='Printify Variant ID - required for POD products', max_length=100),
        ),
    ]
