# Generated by Django 5.0.1 on 2025-12-11 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_add_fulfillment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='fulfillment_type',
            field=models.CharField(choices=[('pod', 'Print on Demand (Printify)'), ('local', 'Local/Vendor (Coach Delivery)')], default='local', help_text='Fulfillment type at time of purchase', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='selected_color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='selected_size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='printify_line_item_id',
            field=models.CharField(blank=True, help_text='Printify Line Item ID for POD products', max_length=100),
        ),
    ]
