# Generated by Django 5.0.1 on 2025-12-11 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_add_orderitem_fulfillment_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printify_variant_id', models.IntegerField(blank=True, help_text='Printify variant ID - required for POD products', null=True)),
                ('title', models.CharField(help_text="Human-readable variant name (e.g., 'Black / XL')", max_length=255)),
                ('size', models.CharField(blank=True, db_index=True, max_length=50)),
                ('color', models.CharField(blank=True, db_index=True, max_length=50)),
                ('color_hex', models.CharField(blank=True, help_text="Hex color code for UI display (e.g., '#1a1a1a')", max_length=7)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Variant-specific price (leave blank to use product base price)', max_digits=10, null=True)),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether this variant is available for purchase')),
                ('is_available', models.BooleanField(default=True, help_text='Stock availability (for POD, this comes from Printify)')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Last sync from Printify', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='payments.product')),
            ],
            options={
                'ordering': ['sort_order', 'size', 'color'],
                'indexes': [models.Index(fields=['product', 'is_enabled'], name='payments_pr_product_84e2f4_idx'), models.Index(fields=['product', 'size'], name='payments_pr_product_b81141_idx'), models.Index(fields=['product', 'color'], name='payments_pr_product_b9e8bf_idx')],
                'unique_together': {('product', 'printify_variant_id')},
            },
        ),
    ]
