# Generated by Django 5.0.1 on 2025-12-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_discontinued',
            field=models.BooleanField(default=False, help_text='Mark product as discontinued/sold out (admin override for POD products)'),
        ),
    ]
