# Generated by Django 5.0.1 on 2025-12-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_add_is_discontinued'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='printify_src',
            field=models.URLField(blank=True, help_text='Original Printify mockup URL (set by sync, do not edit)', max_length=500, null=True),
        ),
    ]
