# Generated by Django 5.0.1 on 2025-12-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_add_printify_src_to_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='printify_variant_ids',
            field=models.JSONField(blank=True, default=list, help_text='List of Printify variant IDs this image shows (set by sync)'),
        ),
    ]
