# Generated by Django 5.0.1 on 2025-12-12 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_add_printify_variant_ids_to_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='title',
            field=models.CharField(blank=True, help_text='Auto-generated from color/size if left blank', max_length=255),
        ),
    ]
