# Generated by Django 5.0.1 on 2025-12-12 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_auto_generate_variant_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('jersey', 'Jersey'), ('hoodie', 'Hoodie'), ('tee', 'T-Shirt'), ('longsleeve', 'Long Sleeve'), ('sweater', 'Sweater'), ('shorts', 'Shorts'), ('hat', 'Hat'), ('bag', 'Bag'), ('accessories', 'Accessories'), ('equipment', 'Equipment'), ('apparel', 'Apparel')], default='apparel', max_length=50),
        ),
    ]
