# Generated by Django 5.0.1 on 2025-12-12 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_expand_category_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='handoff_completed_at',
            field=models.DateTimeField(blank=True, help_text='When the handoff was completed', null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='handoff_completed_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who completed the handoff', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_handoffs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='handoff_notes',
            field=models.TextField(blank=True, help_text='Notes about the handoff (e.g., who picked it up)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='handoff_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending Pickup'), ('ready', 'Ready for Pickup'), ('delivered', 'Delivered')], default='pending', help_text='Status for local product handoffs', max_length=20),
        ),
    ]
