# Generated by Django 5.0.1 on 2025-12-18 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_add_cash_payment_tracking'),
        ('payments', '0017_add_handoff_tracking'),
        ('portal', '0002_add_team_model'),
        ('registrations', '0004_add_cash_payment_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='collected_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who collected cash/in-person payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_collected', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('cash', 'Cash'), ('check', 'Check'), ('handoff', 'Staff Handoff')], default='stripe', help_text='How this order was paid', max_length=20),
        ),
        migrations.CreateModel(
            name='CashPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('payment_for', models.CharField(choices=[('registration', 'Event Registration'), ('product', 'Product Purchase'), ('dues', 'Dues Payment')], help_text='Type of item being paid for', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Cash amount collected (must match item price)', max_digits=10)),
                ('status', models.CharField(choices=[('collected', 'Collected by Staff'), ('handed_off', 'Handed Off to Admin'), ('deposited', 'Deposited to Bank')], default='collected', help_text='Current status in the reconciliation workflow', max_length=20)),
                ('handed_off_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Staff notes about this payment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collected_by', models.ForeignKey(help_text='Staff/Coach who collected this cash payment', on_delete=django.db.models.deletion.PROTECT, related_name='cash_collected', to=settings.AUTH_USER_MODEL)),
                ('dues_account', models.ForeignKey(blank=True, help_text='Link to dues account (if payment_for=dues)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_payments', to='portal.duesaccount')),
                ('event', models.ForeignKey(blank=True, help_text='Event where cash was collected (for context)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_payments', to='events.event')),
                ('event_registration', models.ForeignKey(blank=True, help_text='Link to event registration (if payment_for=registration)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_payments', to='registrations.eventregistration')),
                ('handed_off_to', models.ForeignKey(blank=True, help_text='Admin who received the cash handoff', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_received', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, help_text='Link to product order (if payment_for=product)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_payments', to='payments.order')),
            ],
            options={
                'ordering': ['-collected_at'],
                'indexes': [models.Index(fields=['collected_by', 'status'], name='payments_ca_collect_f3ae57_idx'), models.Index(fields=['status', 'collected_at'], name='payments_ca_status_66bc19_idx'), models.Index(fields=['event', 'status'], name='payments_ca_event_i_9f7ed0_idx')],
            },
        ),
    ]
