# Generated by Django 5.0.1 on 2025-12-18 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_add_cash_payment_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchDropSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, help_text='Enable the merch drop announcement on shop and homepage')),
                ('drop_date', models.DateTimeField(blank=True, help_text='When the merch drop goes live', null=True)),
                ('headline', models.CharField(default='New Drop Incoming', help_text='Main headline for the announcement', max_length=100)),
                ('subheadline', models.CharField(default='Get ready. Something big is coming.', help_text='Secondary text below the headline', max_length=200)),
                ('teaser_text', models.TextField(blank=True, help_text='Optional additional teaser copy')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Merch Drop Settings',
                'verbose_name_plural': 'Merch Drop Settings',
            },
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(blank=True, help_text='Or paste an image URL for the product', max_length=500),
        ),
    ]
